<?php

namespace AppBundle\Repository;

/**
 * CanchaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanchaRepository extends \Doctrine\ORM\EntityRepository
{
}
