AppBundle\Entity\Destinos:
    type: entity
    table: destinos
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        destino:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        dia:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
